#!/bin/bash

APP_NAME=wmetrics
EXECUTABLE_NAME=wmetrics
WIN_EXECUTABLE_NAME=wmetrics.exe

if [ "$GOOS" = "windows" ]; then
    EXECUTABLE_NAME="$WIN_EXECUTABLE_NAME"
fi

[ -f $EXECUTABLE_NAME ] && rm $EXECUTABLE_NAME

go build \
  -ldflags "-X 'github.com/vpominchuk/$APP_NAME/src/app.ExecutableName=$APP_NAME' \
    -X 'github.com/vpominchuk/$APP_NAME/src/app.GitCommit=`git rev-list --count HEAD`' \
    -X 'github.com/vpominchuk/$APP_NAME/src/app.GitTag=`git describe --tags $(git rev-list --tags --max-count=1)`'" \
  -o $EXECUTABLE_NAME
